### ISSUE TITLE
TypeError: socket.close is not a function

### ISSUE THREAD

**Issue by felicienfrancois** [newrelic/node-mitm-server#1]
I get this error when runing the sample code on windows

```
...\node_modules\mitm-server\index.js:110
    if (!proxy.listeners('upgrade').length) return socket.close()
TypeError: socket.close is not a function
    at Server.onUpgrade (...\node_modules\mitm-server\index.js:110:59)
    at emitThree (events.js:97:13)
    at Server.emit (events.js:175:7)
    at onParserExecuteCommon (_http_server.js:394:14)
    at HTTPParser.onParserExecute (_http_server.js:362:5)
```

**Comment by hayes** [comment]
Sorry this took so long to resolve, I had notifications disabled for this repo.  Should be fixed as of v1.4.2
